### ISSUE TITLE
get cloudflare ip range

### ISSUE THREAD

**Issue by rezasa341** [XIU2/CloudflareSpeedTest#269]
Hi. Can you tell me from which source you can get the cloudflare IP range?
The sources I found on the internet were not as complete as the IPs in your repository.
https://www.cloudflare.com/ips/

Thanks

**Comment by XIU2** [comment]
All IP segments in this project are derived from official information provided by Cloudflare: _https://www.cloudflare.com/ips/_
But not all IP segments are Anycast nodes, and not all Anycast node IPs are suitable for domain names with free plans.
Therefore, the IP segment data in this project is simply filtered.

Some unavailable IP segments are removed from the IPv4 data (`ip.txt`), so the IP segments are split so that they appear to be many.
IPv6 data (`ipv6.txt`) contains only part of the available IP segments, because IPv6 is too large and most of them are not enabled. This part of the available IP segments comes from: _https://bgp.he.net/AS13335#_prefixes6_

**Comment by rezasa341** [comment]
Thank you very much
